name       : python-asn1
version    : 0.1.9
release    : 1
source     :
    - http://netassist.dl.sourceforge.net/project/pyasn1/pyasn1/0.1.9/pyasn1-0.1.9.tar.gz : 853cacd96d1f701ddd67aa03ecc05f51890135b7262e922710112f12a2ed2a7f
license    : BSD-3-Clause
summary    : ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language.
description: |
    ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
