name       : python-asn1
version    : 0.4.7
release    : 5
source     :
    - https://files.pythonhosted.org/packages/ca/f8/2a60a2c88a97558bdd289b6dc9eb75b00bd90ff34155d681ba6dbbcb46b2/pyasn1-0.4.7.tar.gz : a9495356ca1d66ed197a0f72b41eb1823cf7ea8b5bd07191673e8147aecf8604
license    : BSD-2-Clause
component  : programming.python
summary    : ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language
description: |
    ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
