name       : python-asn1
version    : 0.5.0
release    : 10
source     :
    - https://github.com/pyasn1/pyasn1/archive/refs/tags/v0.5.0.tar.gz : ce784ab8e00f7cd1c713c6284868dbcfe04930faea0cce2f03b7306f8b8572cc
homepage   : https://github.com/pyasn1/pyasn1
license    : BSD-2-Clause
component  : programming.python
summary    : Generic ASN.1 library for Python 
description: |
    This is a free and open source implementation of ASN.1 types and codecs as a Python package. It has been first written to support particular protocol (SNMP) but then generalized to be suitable for a wide range of protocols based on ASN.1 specification.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
