name       : python-asn1
version    : 0.4.4
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/pyasn1/pyasn1-0.4.4.tar.gz : f58f2a3d12fd754aa123e9fa74fb7345333000a035f3921dbdaa08597aa53137
license    : BSD-2-Clause
component  : programming.python
summary    : ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language
description: |
    ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
