name       : python-asn1
version    : 0.4.8
release    : 9
source     :
    - https://github.com/etingof/pyasn1/archive/refs/tags/v0.4.8.tar.gz : 1baa319ca6e30ffed0d23198d2100742e9e8b5cae464135d69058d0d6069aafc
license    : BSD-2-Clause
component  : programming.python
summary    : ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language
description: |
    ASN.1 types and codecs (BER, CER, DER) implementation in Python programming language.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
